#!/bin/sh
echo '##############################################################'
echo '# shelf.sh'
echo '# Useful shell functions (source from ~/.zshrc)'
echo '##############################################################'
echo
echo 'This file is auto-generated by build.sh. DO NOT EDIT!'
echo
cat shelf/*
