
SHELL := /bin/bash

include-script:
	echo "# auto-generated by 'make include-script'" > shelf.sh; \
	echo "# source this file from ~/.zshrc" >> shelf.sh; \
	echo >> shelf.sh; \
	cat shelf/* >> shelf.sh;
